// Code generated by goctl. DO NOT EDIT.
// Source: rpc.proto

package userservice

import (
	"context"

	"rpc/userRpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMenuReq            = userRpc.AddMenuReq
	AddMenuResp           = userRpc.AddMenuResp
	AddPermissionReq      = userRpc.AddPermissionReq
	AddPermissionResp     = userRpc.AddPermissionResp
	AddRoleReq            = userRpc.AddRoleReq
	AddRoleResp           = userRpc.AddRoleResp
	AdminUserListItem     = userRpc.AdminUserListItem
	AdminUserListReq      = userRpc.AdminUserListReq
	AdminUserListResp     = userRpc.AdminUserListResp
	AdminUserLoginReq     = userRpc.AdminUserLoginReq
	AdminUserLoginResp    = userRpc.AdminUserLoginResp
	CreateAdminUserReq    = userRpc.CreateAdminUserReq
	CreateAdminUserResp   = userRpc.CreateAdminUserResp
	DeleteAdminUserReq    = userRpc.DeleteAdminUserReq
	DeleteAdminUserResp   = userRpc.DeleteAdminUserResp
	DeleteRoleReq         = userRpc.DeleteRoleReq
	DeleteRoleResp        = userRpc.DeleteRoleResp
	DeletedPermissionReq  = userRpc.DeletedPermissionReq
	DeletedPermissionResp = userRpc.DeletedPermissionResp
	GetAdminDetailReq     = userRpc.GetAdminDetailReq
	GetAdminDetailResp    = userRpc.GetAdminDetailResp
	GetAllMenuReq         = userRpc.GetAllMenuReq
	GetAllMenuResp        = userRpc.GetAllMenuResp
	GetMenuByAdminIdItem  = userRpc.GetMenuByAdminIdItem
	GetMenuByAdminIdReq   = userRpc.GetMenuByAdminIdReq
	GetMenuByAdminIdResp  = userRpc.GetMenuByAdminIdResp
	GetMenuListReq        = userRpc.GetMenuListReq
	GetMenuListResp       = userRpc.GetMenuListResp
	GetPermissionListReq  = userRpc.GetPermissionListReq
	GetPermissionListResp = userRpc.GetPermissionListResp
	GetRoleListReq        = userRpc.GetRoleListReq
	GetRoleListResp       = userRpc.GetRoleListResp
	GetUserDetailByIdReq  = userRpc.GetUserDetailByIdReq
	GetUserDetailByIdResp = userRpc.GetUserDetailByIdResp
	GetUserListByIdsReq   = userRpc.GetUserListByIdsReq
	GetUserListByIdsResp  = userRpc.GetUserListByIdsResp
	GetUserListByPageReq  = userRpc.GetUserListByPageReq
	GetUserListByPageResp = userRpc.GetUserListByPageResp
	LoginByAccountReq     = userRpc.LoginByAccountReq
	LoginByAccountResp    = userRpc.LoginByAccountResp
	LoginByEmailReq       = userRpc.LoginByEmailReq
	LoginByEmailResp      = userRpc.LoginByEmailResp
	LogoutReq             = userRpc.LogoutReq
	LogoutResp            = userRpc.LogoutResp
	ParseTokenReq         = userRpc.ParseTokenReq
	ParseTokenResp        = userRpc.ParseTokenResp
	RegisterByAccountReq  = userRpc.RegisterByAccountReq
	RegisterByAccountResp = userRpc.RegisterByAccountResp
	RegisterByEmailReq    = userRpc.RegisterByEmailReq
	RegisterByEmailResp   = userRpc.RegisterByEmailResp
	UpdateAdminDetailReq  = userRpc.UpdateAdminDetailReq
	UpdateAdminDetailResp = userRpc.UpdateAdminDetailResp
	UpdateMenuReq         = userRpc.UpdateMenuReq
	UpdateMenuResp        = userRpc.UpdateMenuResp
	UpdatePermissionReq   = userRpc.UpdatePermissionReq
	UpdatePermissionResp  = userRpc.UpdatePermissionResp
	UpdateRoleReq         = userRpc.UpdateRoleReq
	UpdateRoleResp        = userRpc.UpdateRoleResp
	UpdateUserByIdReq     = userRpc.UpdateUserByIdReq
	UpdateUserByIdResp    = userRpc.UpdateUserByIdResp

	UserService interface {
		GetUserDetailById(ctx context.Context, in *GetUserDetailByIdReq, opts ...grpc.CallOption) (*GetUserDetailByIdResp, error)
		UpdateUserById(ctx context.Context, in *UpdateUserByIdReq, opts ...grpc.CallOption) (*UpdateUserByIdResp, error)
		GetUserListByPage(ctx context.Context, in *GetUserListByPageReq, opts ...grpc.CallOption) (*GetUserListByPageResp, error)
		GetUserListByIds(ctx context.Context, in *GetUserListByIdsReq, opts ...grpc.CallOption) (*GetUserListByIdsResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetUserDetailById(ctx context.Context, in *GetUserDetailByIdReq, opts ...grpc.CallOption) (*GetUserDetailByIdResp, error) {
	client := userRpc.NewUserServiceClient(m.cli.Conn())
	return client.GetUserDetailById(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserById(ctx context.Context, in *UpdateUserByIdReq, opts ...grpc.CallOption) (*UpdateUserByIdResp, error) {
	client := userRpc.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserById(ctx, in, opts...)
}

func (m *defaultUserService) GetUserListByPage(ctx context.Context, in *GetUserListByPageReq, opts ...grpc.CallOption) (*GetUserListByPageResp, error) {
	client := userRpc.NewUserServiceClient(m.cli.Conn())
	return client.GetUserListByPage(ctx, in, opts...)
}

func (m *defaultUserService) GetUserListByIds(ctx context.Context, in *GetUserListByIdsReq, opts ...grpc.CallOption) (*GetUserListByIdsResp, error) {
	client := userRpc.NewUserServiceClient(m.cli.Conn())
	return client.GetUserListByIds(ctx, in, opts...)
}
