// Code generated by goctl. DO NOT EDIT.
// Source: rpc.proto

package roleauthservice

import (
	"context"

	"github.com/doubunv/rpc-client/user-rpc/userRpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMenuReq            = userRpc.AddMenuReq
	AddMenuResp           = userRpc.AddMenuResp
	AddPermissionReq      = userRpc.AddPermissionReq
	AddPermissionResp     = userRpc.AddPermissionResp
	AddRoleReq            = userRpc.AddRoleReq
	AddRoleResp           = userRpc.AddRoleResp
	AdminUserListItem     = userRpc.AdminUserListItem
	AdminUserListReq      = userRpc.AdminUserListReq
	AdminUserListResp     = userRpc.AdminUserListResp
	AdminUserLoginReq     = userRpc.AdminUserLoginReq
	AdminUserLoginResp    = userRpc.AdminUserLoginResp
	CreateAdminUserReq    = userRpc.CreateAdminUserReq
	CreateAdminUserResp   = userRpc.CreateAdminUserResp
	DeleteAdminUserReq    = userRpc.DeleteAdminUserReq
	DeleteAdminUserResp   = userRpc.DeleteAdminUserResp
	DeleteRoleReq         = userRpc.DeleteRoleReq
	DeleteRoleResp        = userRpc.DeleteRoleResp
	DeletedPermissionReq  = userRpc.DeletedPermissionReq
	DeletedPermissionResp = userRpc.DeletedPermissionResp
	GetAdminDetailReq     = userRpc.GetAdminDetailReq
	GetAdminDetailResp    = userRpc.GetAdminDetailResp
	GetAllMenuReq         = userRpc.GetAllMenuReq
	GetAllMenuResp        = userRpc.GetAllMenuResp
	GetMenuByAdminIdItem  = userRpc.GetMenuByAdminIdItem
	GetMenuByAdminIdReq   = userRpc.GetMenuByAdminIdReq
	GetMenuByAdminIdResp  = userRpc.GetMenuByAdminIdResp
	GetMenuListReq        = userRpc.GetMenuListReq
	GetMenuListResp       = userRpc.GetMenuListResp
	GetPermissionListReq  = userRpc.GetPermissionListReq
	GetPermissionListResp = userRpc.GetPermissionListResp
	GetRoleListReq        = userRpc.GetRoleListReq
	GetRoleListResp       = userRpc.GetRoleListResp
	GetUserDetailByIdReq  = userRpc.GetUserDetailByIdReq
	GetUserDetailByIdResp = userRpc.GetUserDetailByIdResp
	GetUserListByIdsReq   = userRpc.GetUserListByIdsReq
	GetUserListByIdsResp  = userRpc.GetUserListByIdsResp
	GetUserListByPageReq  = userRpc.GetUserListByPageReq
	GetUserListByPageResp = userRpc.GetUserListByPageResp
	LoginByAccountReq     = userRpc.LoginByAccountReq
	LoginByAccountResp    = userRpc.LoginByAccountResp
	LoginByEmailReq       = userRpc.LoginByEmailReq
	LoginByEmailResp      = userRpc.LoginByEmailResp
	LogoutReq             = userRpc.LogoutReq
	LogoutResp            = userRpc.LogoutResp
	ParseTokenReq         = userRpc.ParseTokenReq
	ParseTokenResp        = userRpc.ParseTokenResp
	RegisterByAccountReq  = userRpc.RegisterByAccountReq
	RegisterByAccountResp = userRpc.RegisterByAccountResp
	RegisterByEmailReq    = userRpc.RegisterByEmailReq
	RegisterByEmailResp   = userRpc.RegisterByEmailResp
	UpdateAdminDetailReq  = userRpc.UpdateAdminDetailReq
	UpdateAdminDetailResp = userRpc.UpdateAdminDetailResp
	UpdateMenuReq         = userRpc.UpdateMenuReq
	UpdateMenuResp        = userRpc.UpdateMenuResp
	UpdatePermissionReq   = userRpc.UpdatePermissionReq
	UpdatePermissionResp  = userRpc.UpdatePermissionResp
	UpdateRoleReq         = userRpc.UpdateRoleReq
	UpdateRoleResp        = userRpc.UpdateRoleResp
	UpdateUserByIdReq     = userRpc.UpdateUserByIdReq
	UpdateUserByIdResp    = userRpc.UpdateUserByIdResp

	RoleAuthService interface {
		// 权限板块
		AddPermission(ctx context.Context, in *AddPermissionReq, opts ...grpc.CallOption) (*AddPermissionResp, error)
		DeletedPermission(ctx context.Context, in *DeletedPermissionReq, opts ...grpc.CallOption) (*DeletedPermissionResp, error)
		UpdatePermission(ctx context.Context, in *UpdatePermissionReq, opts ...grpc.CallOption) (*UpdatePermissionResp, error)
		GetPermissionList(ctx context.Context, in *GetPermissionListReq, opts ...grpc.CallOption) (*GetPermissionListResp, error)
		// 角色管理
		AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error)
		UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error)
		DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error)
		GetRoleList(ctx context.Context, in *GetRoleListReq, opts ...grpc.CallOption) (*GetRoleListResp, error)
		// 菜单板块
		AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuResp, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error)
		GetMenuList(ctx context.Context, in *GetMenuListReq, opts ...grpc.CallOption) (*GetMenuListResp, error)
		GetAllMenu(ctx context.Context, in *GetAllMenuReq, opts ...grpc.CallOption) (*GetAllMenuResp, error)
		GetMenuByAdminId(ctx context.Context, in *GetMenuByAdminIdReq, opts ...grpc.CallOption) (*GetMenuByAdminIdResp, error)
	}

	defaultRoleAuthService struct {
		cli zrpc.Client
	}
)

func NewRoleAuthService(cli zrpc.Client) RoleAuthService {
	return &defaultRoleAuthService{
		cli: cli,
	}
}

// 权限板块
func (m *defaultRoleAuthService) AddPermission(ctx context.Context, in *AddPermissionReq, opts ...grpc.CallOption) (*AddPermissionResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.AddPermission(ctx, in, opts...)
}

func (m *defaultRoleAuthService) DeletedPermission(ctx context.Context, in *DeletedPermissionReq, opts ...grpc.CallOption) (*DeletedPermissionResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.DeletedPermission(ctx, in, opts...)
}

func (m *defaultRoleAuthService) UpdatePermission(ctx context.Context, in *UpdatePermissionReq, opts ...grpc.CallOption) (*UpdatePermissionResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.UpdatePermission(ctx, in, opts...)
}

func (m *defaultRoleAuthService) GetPermissionList(ctx context.Context, in *GetPermissionListReq, opts ...grpc.CallOption) (*GetPermissionListResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.GetPermissionList(ctx, in, opts...)
}

// 角色管理
func (m *defaultRoleAuthService) AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.AddRole(ctx, in, opts...)
}

func (m *defaultRoleAuthService) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultRoleAuthService) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultRoleAuthService) GetRoleList(ctx context.Context, in *GetRoleListReq, opts ...grpc.CallOption) (*GetRoleListResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}

// 菜单板块
func (m *defaultRoleAuthService) AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.AddMenu(ctx, in, opts...)
}

func (m *defaultRoleAuthService) UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultRoleAuthService) GetMenuList(ctx context.Context, in *GetMenuListReq, opts ...grpc.CallOption) (*GetMenuListResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.GetMenuList(ctx, in, opts...)
}

func (m *defaultRoleAuthService) GetAllMenu(ctx context.Context, in *GetAllMenuReq, opts ...grpc.CallOption) (*GetAllMenuResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.GetAllMenu(ctx, in, opts...)
}

func (m *defaultRoleAuthService) GetMenuByAdminId(ctx context.Context, in *GetMenuByAdminIdReq, opts ...grpc.CallOption) (*GetMenuByAdminIdResp, error) {
	client := userRpc.NewRoleAuthServiceClient(m.cli.Conn())
	return client.GetMenuByAdminId(ctx, in, opts...)
}
