// Code generated by goctl. DO NOT EDIT.
// Source: rpc.proto

package adminuser

import (
	"context"
	"github.com/doubunv/rpc-client/user-rpc/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminUserLoginReq  = rpc.AdminUserLoginReq
	AdminUserLoginResp = rpc.AdminUserLoginResp
	LoginRoleMenuItem  = rpc.LoginRoleMenuItem

	AdminUser interface {
		// 管理员登录
		UserLogin(ctx context.Context, in *AdminUserLoginReq, opts ...grpc.CallOption) (*AdminUserLoginResp, error)
	}

	defaultAdminUser struct {
		cli zrpc.Client
	}
)

func NewAdminUser(cli zrpc.Client) AdminUser {
	return &defaultAdminUser{
		cli: cli,
	}
}

// 管理员登录
func (m *defaultAdminUser) UserLogin(ctx context.Context, in *AdminUserLoginReq, opts ...grpc.CallOption) (*AdminUserLoginResp, error) {
	client := rpc.NewAdminUserClient(m.cli.Conn())
	return client.UserLogin(ctx, in, opts...)
}
