// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.4
// source: dsl/rpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUserLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`   //账号，系统唯一
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` //密码
}

func (x *AdminUserLoginReq) Reset() {
	*x = AdminUserLoginReq{}
	mi := &file_dsl_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserLoginReq) ProtoMessage() {}

func (x *AdminUserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserLoginReq.ProtoReflect.Descriptor instead.
func (*AdminUserLoginReq) Descriptor() ([]byte, []int) {
	return file_dsl_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUserLoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AdminUserLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRoleMenuItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`             //菜单ID
	MenuName string               `protobuf:"bytes,2,opt,name=menuName,proto3" json:"menuName,omitempty"`  //菜单名字
	Path     string               `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`          //菜单路径地址
	MenuPid  int64                `protobuf:"varint,4,opt,name=menuPid,proto3" json:"menuPid,omitempty"`   //父级ID
	MenuType int32                `protobuf:"varint,5,opt,name=menuType,proto3" json:"menuType,omitempty"` // 1=菜单，2=按钮
	Children []*LoginRoleMenuItem `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`  //子级菜单
}

func (x *LoginRoleMenuItem) Reset() {
	*x = LoginRoleMenuItem{}
	mi := &file_dsl_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRoleMenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRoleMenuItem) ProtoMessage() {}

func (x *LoginRoleMenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRoleMenuItem.ProtoReflect.Descriptor instead.
func (*LoginRoleMenuItem) Descriptor() ([]byte, []int) {
	return file_dsl_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRoleMenuItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginRoleMenuItem) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *LoginRoleMenuItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LoginRoleMenuItem) GetMenuPid() int64 {
	if x != nil {
		return x.MenuPid
	}
	return 0
}

func (x *LoginRoleMenuItem) GetMenuType() int32 {
	if x != nil {
		return x.MenuType
	}
	return 0
}

func (x *LoginRoleMenuItem) GetChildren() []*LoginRoleMenuItem {
	if x != nil {
		return x.Children
	}
	return nil
}

type AdminUserLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token            string               `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                       //登录成功返回的token
	RoleMenuItemList []*LoginRoleMenuItem `protobuf:"bytes,2,rep,name=roleMenuItemList,proto3" json:"roleMenuItemList,omitempty"` //登录成功后返回的菜单信息
}

func (x *AdminUserLoginResp) Reset() {
	*x = AdminUserLoginResp{}
	mi := &file_dsl_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserLoginResp) ProtoMessage() {}

func (x *AdminUserLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserLoginResp.ProtoReflect.Descriptor instead.
func (*AdminUserLoginResp) Descriptor() ([]byte, []int) {
	return file_dsl_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *AdminUserLoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminUserLoginResp) GetRoleMenuItemList() []*LoginRoleMenuItem {
	if x != nil {
		return x.RoleMenuItemList
	}
	return nil
}

var File_dsl_rpc_proto protoreflect.FileDescriptor

var file_dsl_rpc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x73, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x72, 0x70, 0x63, 0x22, 0x49, 0x0a, 0x11, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0xbd, 0x01, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x65, 0x6e,
	0x75, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x75, 0x50, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x75, 0x50, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x65, 0x6e,
	0x75, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22,
	0x6e, 0x0a, 0x12, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x42, 0x0a, 0x10, 0x72,
	0x6f, 0x6c, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10, 0x72,
	0x6f, 0x6c, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x32,
	0x49, 0x0a, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dsl_rpc_proto_rawDescOnce sync.Once
	file_dsl_rpc_proto_rawDescData = file_dsl_rpc_proto_rawDesc
)

func file_dsl_rpc_proto_rawDescGZIP() []byte {
	file_dsl_rpc_proto_rawDescOnce.Do(func() {
		file_dsl_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_dsl_rpc_proto_rawDescData)
	})
	return file_dsl_rpc_proto_rawDescData
}

var file_dsl_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dsl_rpc_proto_goTypes = []any{
	(*AdminUserLoginReq)(nil),  // 0: rpc.AdminUserLoginReq
	(*LoginRoleMenuItem)(nil),  // 1: rpc.LoginRoleMenuItem
	(*AdminUserLoginResp)(nil), // 2: rpc.AdminUserLoginResp
}
var file_dsl_rpc_proto_depIdxs = []int32{
	1, // 0: rpc.LoginRoleMenuItem.children:type_name -> rpc.LoginRoleMenuItem
	1, // 1: rpc.AdminUserLoginResp.roleMenuItemList:type_name -> rpc.LoginRoleMenuItem
	0, // 2: rpc.AdminUser.userLogin:input_type -> rpc.AdminUserLoginReq
	2, // 3: rpc.AdminUser.userLogin:output_type -> rpc.AdminUserLoginResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dsl_rpc_proto_init() }
func file_dsl_rpc_proto_init() {
	if File_dsl_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dsl_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dsl_rpc_proto_goTypes,
		DependencyIndexes: file_dsl_rpc_proto_depIdxs,
		MessageInfos:      file_dsl_rpc_proto_msgTypes,
	}.Build()
	File_dsl_rpc_proto = out.File
	file_dsl_rpc_proto_rawDesc = nil
	file_dsl_rpc_proto_goTypes = nil
	file_dsl_rpc_proto_depIdxs = nil
}
